repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.13.0"
    hooks:
      - id: mypy
        args:
          - --strict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.8.3"
    hooks:
      - id: ruff
        additional_dependencies:
        - ruff[pyproject]
        args:
          - --fix


default_language_version:
  python: python3.12